name: d3r
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9.13 
  - pip
  - ffmpeg=5.*
  - poetry=1.*
  - conda-lock=1.*
  - pytorch::pytorch=1.11.0
  - pytorch::pytorch-cuda=11.*